### ISSUE TITLE
External Page Componetn code not compatible with Content Hub v4.2.x and newer

### ISSUE THREAD

**Issue by jorgenjanssonlee** [robhabraken/content-hub-focal-point-cropping#4]
Just raising this for awareness, Not expecting a fix, but hoping for one anyway... :)

The external page component implementation in Content Hub has changed since they moved to React (v4.2.?), and this code is no longer compatible.
External page components now need to use a JS or React bundle, there is no option to specify separate HTML and CSS in Content Hub, it needs to be part of the bundle. See https://docs-partners.stylelabs.com/contenthub/4.2.x/content/integrations/integration-components/external-page-component/configure-external-component.html

**Comment by robhabraken** [comment]
Thanks for pointing this out to me Jorgen! It took a bit longer than intended, but I just released a new 4.2 compatible version of my external page components.
